require("js/egret.min.js")
require("js/eui.min.js")
require("js/assetsmanager.min.js")
require("js/tween.min.js")
require("js/game.min.js")
require("js/is.min.js")
require("js/base64.min.js")
var pathf=require('js/PathFinding.min.js');pathf['DiagonalMovement']=window.PF.DiagonalMovement;pathf['Option']=window.PF.Option;window.PF=pathf;
window.JSZip = require("js/jszip.min.js")
require("js/default.thm_290911fc.js")
require("js/main.min.js")